server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: contact-service
          uri: lb://contact-ms          # must match spring.application.name of contact MS
          predicates:
            - Path=/contacts/**

        - id: user-service
          uri: lb://user-ms             # must match spring.application.name of user MS
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
