spring:
    application:
       name: APIGateway
    cloud:
        gateway:
          routes:
            - id:  user-ms
              uri: lb://user-ms
              predicates:
                - Path=/user/**
            - id: contact-ms
              uri: lb://contact-ms
              predicates:
                - Path=/contacts/**


management:
 endpoints: 
  web:
   exposure:
    include: health,info			
