spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: contact-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/contacts/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
